# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 05:28
from __future__ import unicode_literals

import admin_sort.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Another',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Title')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('my_order', '-title'),
            },
        ),
        migrations.CreateModel(
            name='AnotherOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_field', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Note2')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('my_order',),
            },
            bases=(admin_sort.models.SortableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Title')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='ChapterExtraZero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Title')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('my_order', '-title'),
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Note')),
                ('another_field', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Note2')),
                ('one_more', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Note3 (simulating tabular inlines)')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='NotesExtraZero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('another_field', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Note2')),
                ('my_order', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('my_order', 'another_field'),
            },
        ),
        migrations.CreateModel(
            name='SortableBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Title')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Author')),
            ],
            options={
                'ordering': ('my_order',),
            },
        ),
        migrations.AddField(
            model_name='notesextrazero',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
        migrations.AddField(
            model_name='notes',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
        migrations.AddField(
            model_name='chapterextrazero',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
        migrations.AddField(
            model_name='anotherone',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
        migrations.AddField(
            model_name='another',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.SortableBook'),
        ),
    ]
