# Generated by Django 2.1.2 on 2018-11-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherSortableBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('my_order',),
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('my_order', 'another_order')},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('my_order', 'another_order')},
        ),
        migrations.AddField(
            model_name='chapter',
            name='another_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='another_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='another',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='anotherone',
            name='another_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note2'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chapterextrazero',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='another_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note2'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='one_more',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note3 (simulating tabular inlines)'),
        ),
        migrations.AlterField(
            model_name='notesextrazero',
            name='another_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note2'),
        ),
        migrations.AlterField(
            model_name='sortablebook',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='anothersortablebook',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Author'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='another_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.AnotherSortableBook'),
        ),
        migrations.AddField(
            model_name='notes',
            name='another_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.AnotherSortableBook'),
        ),
    ]
