# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_chapterextrazero_notesextrazero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='my_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapterextrazero',
            name='my_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='my_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notesextrazero',
            name='my_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
