# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20181026_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
